// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package store

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const CreateMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, year, runtime , genres) VALUES ($1, $2, $3, $4) RETURNING id, title, year, runtime, genres, created_at, updated_at, deleted_at
`

type CreateMovieParams struct {
	Title   string   `db:"title" json:"title"`
	Year    int32    `db:"year" json:"year"`
	Runtime int32    `db:"runtime" json:"runtime"`
	Genres  []string `db:"genres" json:"genres"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.queryRow(ctx, q.createMovieStmt, CreateMovie,
		arg.Title,
		arg.Year,
		arg.Runtime,
		pq.Array(arg.Genres),
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		pq.Array(&i.Genres),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const DeleteMovie = `-- name: DeleteMovie :exec
UPDATE movies
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteMovieStmt, DeleteMovie, id)
	return err
}

const GetMovie = `-- name: GetMovie :one
SELECT id, title, year, runtime, genres, created_at, updated_at, deleted_at FROM movies 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, id int32) (Movie, error) {
	row := q.queryRow(ctx, q.getMovieStmt, GetMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		pq.Array(&i.Genres),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const ListMovies = `-- name: ListMovies :many
SELECT id, title, year, runtime, genres, created_at, updated_at, deleted_at FROM movies 
WHERE genres && $3 
ORDER BY runtime
LIMIT $1 OFFSET $2
`

type ListMoviesParams struct {
	Limit  int64    `db:"limit" json:"limit"`
	Offset int64    `db:"offset" json:"offset"`
	Genres []string `db:"genres" json:"genres"`
}

func (q *Queries) ListMovies(ctx context.Context, arg ListMoviesParams) ([]Movie, error) {
	rows, err := q.query(ctx, q.listMoviesStmt, ListMovies, arg.Limit, arg.Offset, pq.Array(arg.Genres))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Year,
			&i.Runtime,
			pq.Array(&i.Genres),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateMovie = `-- name: UpdateMovie :one
UPDATE movies 
SET title = CASE WHEN $1 <> '' THEN $1::VARCHAR(50) ELSE title END,
    year = CASE WHEN $2 <> 0 THEN $2::INTEGER ELSE year END,
    runtime = CASE WHEN $3 > 0 THEN $3::INTEGER ELSE runtime END
WHERE id = $4
RETURNING id, title, year, runtime, genres, created_at, updated_at, deleted_at
`

type UpdateMovieParams struct {
	Title   sql.NullString `db:"title" json:"title"`
	Year    sql.NullInt32  `db:"year" json:"year"`
	Runtime sql.NullInt32  `db:"runtime" json:"runtime"`
	ID      int32          `db:"id" json:"id"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.queryRow(ctx, q.updateMovieStmt, UpdateMovie,
		arg.Title,
		arg.Year,
		arg.Runtime,
		arg.ID,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Runtime,
		pq.Array(&i.Genres),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
