CREATE TABLE movies (
    id INTEGER PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    year INTEGER NOT NULL,
    runtime INTEGER NOT NULL,
    genres VARCHAR(20) [] NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);